#!/bin/bash

# VPS Automated Setup Script
# This script automates the initial VPS setup for MIC Backend
# Run on your VPS: bash setup-vps.sh

set -e

echo "🚀 MIC Backend VPS Setup Script"
echo "================================"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
  echo -e "${RED}❌ Please run as root (use: sudo bash setup-vps.sh)${NC}"
  exit 1
fi

# Variables
APP_PATH="/var/www/mic-backend"
GITHUB_REPO="${1:-}"
BACKEND_DOMAIN="${2:-api.mic.xfinai.cloud}"
FRONTEND_DOMAIN="${3:-admin.mic.xfinai.cloud}"
BACKEND_PORT="5000"

# Function to print colored output
print_status() {
  echo -e "${GREEN}✓${NC} $1"
}

print_error() {
  echo -e "${RED}✗${NC} $1"
}

print_info() {
  echo -e "${YELLOW}ℹ${NC} $1"
}

# Step 1: Update system
print_info "Step 1: Updating system packages..."
apt-get update
apt-get upgrade -y
print_status "System updated"

# Step 2: Install Node.js
print_info "Step 2: Installing Node.js 20.x..."
if ! command -v node &> /dev/null; then
  curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  apt-get install -y nodejs
  print_status "Node.js installed: $(node --version)"
else
  print_status "Node.js already installed: $(node --version)"
fi

# Step 3: Install Git
print_info "Step 3: Installing Git..."
apt-get install -y git
print_status "Git installed: $(git --version)"

# Step 4: Create application directory
print_info "Step 4: Creating application directory..."
mkdir -p "$APP_PATH"
print_status "Directory created: $APP_PATH"

# Step 5: Clone repository
if [ -z "$GITHUB_REPO" ]; then
  print_error "GitHub repository URL not provided"
  echo "Usage: sudo bash setup-vps.sh https://github.com/YOUR-USERNAME/MIC.git"
  exit 1
fi

print_info "Step 5: Cloning repository..."
if [ ! -d "$APP_PATH/.git" ]; then
  git clone "$GITHUB_REPO" "$APP_PATH"
  print_status "Repository cloned"
else
  print_status "Repository already exists"
fi

# Step 6: Install backend dependencies
print_info "Step 6: Installing backend dependencies..."
cd "$APP_PATH/backend"
npm install
print_status "Dependencies installed"

# Step 7: Create .env file
print_info "Step 7: Checking for .env file..."
if [ ! -f "$APP_PATH/backend/.env" ]; then
  print_error ".env file not found"
  echo "Please create $APP_PATH/backend/.env with required variables:"
  echo "  NODE_ENV=production"
  echo "  DATABASE_URL=mongodb+srv://..."
  echo "  JWT_SECRET=your-secret"
  echo "  PORT=$BACKEND_PORT"
  echo ""
  read -p "Press Enter after .env is created..."
  
  if [ ! -f "$APP_PATH/backend/.env" ]; then
    print_error ".env file still not found. Setup cannot continue."
    exit 1
  fi
else
  print_status ".env file exists"
fi

# Step 8: Create systemd service
print_info "Step 8: Creating systemd service..."
cat > /etc/systemd/system/mic-backend.service << EOF
[Unit]
Description=MIC Backend Service
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=$APP_PATH/backend
ExecStart=/usr/bin/node src/server.js
Restart=on-failure
RestartSec=10
Environment="NODE_ENV=production"

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable mic-backend
print_status "Systemd service created and enabled"

# Step 9: Start the service
print_info "Step 9: Starting backend service..."
systemctl start mic-backend
sleep 2

if systemctl is-active --quiet mic-backend; then
  print_status "Backend service is running!"
else
  print_error "Backend service failed to start"
  echo "Check logs with: sudo journalctl -u mic-backend -n 50"
  exit 1
fi

# Step 10: Configure Git for deployments
print_info "Step 10: Configuring Git..."
cd "$APP_PATH"
git config user.email "deployment@example.com"
git config user.name "Deployment Bot"
print_status "Git configured"

# Step 11: Install and configure Nginx
print_info "Step 11: Installing and configuring Nginx..."
apt-get install -y nginx
FRONTEND_PATH="/var/www/mic-frontend"
mkdir -p "$FRONTEND_PATH"

# Create Nginx configuration for Admin Panel
cat > /etc/nginx/sites-available/mic-admin << 'NGINX_CONFIG'
server {
    listen 80;
    listen [::]:80;
    server_name $FRONTEND_DOMAIN;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $FRONTEND_DOMAIN;

    # SSL certificates (will be generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/$FRONTEND_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$FRONTEND_DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Admin Panel (Frontend)
    location / {
        root /var/www/mic-frontend;
        try_files $uri $uri/ /index.html;
        expires 1h;
        add_header Cache-Control "public, immutable";
    }

    # Assets with long cache
    location ~* \.(js|css|woff|woff2|ttf|eot|svg|png|jpg|jpeg|gif|webp)$ {
        root /var/www/mic-frontend;
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css text/xml text/javascript 
               application/x-javascript application/xml+rss 
               application/javascript application/json;
}
NGINX_CONFIG

# Create Nginx configuration for API
cat > /etc/nginx/sites-available/mic-api << 'NGINX_API_CONFIG'
server {
    listen 80;
    listen [::]:80;
    server_name $BACKEND_DOMAIN;

    # Let's Encrypt ACME challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Redirect HTTP to HTTPS
    location / {
        return 301 https://$server_name$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $BACKEND_DOMAIN;

    # SSL certificates (will be generated by Certbot)
    ssl_certificate /etc/letsencrypt/live/$BACKEND_DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$BACKEND_DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # API Proxy to Node.js backend
    location / {
        proxy_pass http://localhost:$BACKEND_PORT;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 60s;
        proxy_connect_timeout 60s;
    }

    # Gzip compression
    gzip on;
    gzip_types text/plain text/css text/xml text/javascript 
               application/x-javascript application/xml+rss 
               application/javascript application/json;
}
NGINX_API_CONFIG

# Create certbot directory for ACME challenges
mkdir -p /var/www/certbot

# Enable Nginx sites
ln -sf /etc/nginx/sites-available/mic-admin /etc/nginx/sites-enabled/mic-admin
ln -sf /etc/nginx/sites-available/mic-api /etc/nginx/sites-enabled/mic-api
rm -f /etc/nginx/sites-enabled/default

# Test Nginx configuration (with domain variables substituted)
if nginx -t 2>&1 | grep -q "test is successful"; then
  print_status "Nginx configuration is valid"
else
  print_info "Nginx will be configured after SSL setup"
fi

# Enable Nginx service
systemctl enable nginx
systemctl restart nginx 2>/dev/null || true

# Install Let's Encrypt Certbot for SSL certificates
print_info "Step 12: Installing Certbot for SSL certificates..."
apt-get install -y certbot python3-certbot-nginx

# Create SSL certificates
print_info "Step 13: Setting up SSL certificates..."
mkdir -p /var/www/certbot

# Request SSL certificates for both domains
print_info "Requesting SSL certificate for Frontend domain ($FRONTEND_DOMAIN)..."
certbot certonly --webroot -w /var/www/certbot -d "$FRONTEND_DOMAIN" --non-interactive --agree-tos -m admin@xfinai.cloud 2>/dev/null || print_info "Frontend certificate setup - you may need to run manually"

print_info "Requesting SSL certificate for API domain ($BACKEND_DOMAIN)..."
certbot certonly --webroot -w /var/www/certbot -d "$BACKEND_DOMAIN" --non-interactive --agree-tos -m admin@xfinai.cloud 2>/dev/null || print_info "API certificate setup - you may need to run manually"

# Reload Nginx to apply SSL certificates
systemctl reload nginx
print_status "Nginx configured with SSL certificates"

# Print summary
echo ""
echo "========================================"
echo -e "${GREEN}✓ VPS Setup Complete!${NC}"
echo "========================================"
echo ""
echo "📍 Backend Path: $APP_PATH"
echo "📍 Frontend Path: $FRONTEND_PATH"
echo "🔧 Backend Port: $BACKEND_PORT (via Node.js)"
echo "🌐 Nginx Port: 80/443 (reverse proxy)"
echo ""
echo "Your Domains:"
echo "  ✅ Frontend (Admin Panel): https://$FRONTEND_DOMAIN"
echo "  ✅ Backend API: https://$BACKEND_DOMAIN"
echo ""
echo "DNS Configuration Required:"
echo "Add these CNAME records to your xfinai.cloud domain:"
echo "  admin.mic  → your-vps-ip-or-domain"
echo "  api.mic    → your-vps-ip-or-domain"
echo ""
echo "Next steps:"
echo "1. Configure DNS records (see above)"
echo ""
echo "2. Verify SSL certificates:"
echo "   ls -la /etc/letsencrypt/live/$FRONTEND_DOMAIN/"
echo "   ls -la /etc/letsencrypt/live/$BACKEND_DOMAIN/"
echo ""
echo "3. Test backend is running:"
echo "   sudo systemctl status mic-backend"
echo ""
echo "4. View backend logs:"
echo "   sudo journalctl -u mic-backend -f"
echo ""
echo "5. View Nginx logs:"
echo "   sudo tail -f /var/log/nginx/access.log"
echo ""
echo "5. Add SSH key to GitHub:"
echo "   - Generate: ssh-keygen -t ed25519 -f ~/.ssh/github-deploy -N \"\""
echo "   - Add to GitHub Secrets:"
echo "     * VPS_PRIVATE_KEY: Content of ~/.ssh/github-deploy"
echo "     * VPS_HOST: Your VPS IP"
echo "     * VPS_USER: root"
echo "     * VPS_APP_PATH: $APP_PATH"
echo "     * VPS_FRONTEND_PATH: $FRONTEND_PATH"
echo "   - See: $APP_PATH/.github/VPS-SETUP.md for details"
echo ""
